blank_issues_enabled: false
contact_links:
    - name: Discord Chat
      url:
      about: Ask questions and discuss with other Vben users in real time.
    - name: Questions & Discussions
      url: https://github.com/gbowne1/codebooker/discussions
      about: Use GitHub discussions for message-board style questions and discussions.
